---
title: Getting started with Raspberry Pi Pico
hero_image: images/banner.png
description: How to start programming you Raspberry Pi Pico with Thonny and MicroPython
version: 4
listed: true
copyedit: true
last_tested: '2020-10-14'
steps:
- title: What you will do
- title: Meet Raspberry Pi Pico
- title: Install or update Thonny
  completion:
  - engaged
- title: Add the MicroPython firmware
- title: Blink the onboard LED
- title: Write a longer program
- title: Use digital inputs and outputs
- title: Control LED brightness
- title: Control an LED with an analogue input
- title: Run from a power supply
  completion:
  - internal
- title: What can you do now?
  completion:
  - external
