title: getting-started-with-the
hero_image: images/banner.png
description: getting-started-with-the description
version: 4
listed: false
copyedit: false
last_tested: "2020-10-14"
steps:
  - title: Introduction
  - title: Meet X
  - title: Connect X to your computer
  - title: Add the micropython firmware
  - title: Install Thonny
  - title: Blink the onboard LED
  - title: Use digital inputs and outputs
  - title: Use an analogue input
  - title: Control LED brightness with PWM
  - title: Power your X
  - title: What next?
